{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-debugme
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/debugme_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/debugme/debugme_{{ version }}.tar.gz
  sha256: b22605ad3b20d460308d8c9c18116e56c4d6ff10577608eaf58802998171f099

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon
  run:
    - r-base
    - r-crayon

test:
  commands:
    - $R -e "library('debugme')"           # [not win]
    - "\"%R%\" -e \"library('debugme')\""  # [win]

about:
  home: https://github.com/r-lib/debugme#readme
  license: MIT
  summary: Specify debug messages as special string constants, and control debugging of packages via environment variables.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
