# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eFi7m9gaQBszoo7Mbvth2ewj/DCvL3rozv3PwN43Dok5CvkLlK54X2CojhVb2bK7+cOZjiEZwBdNQfPOjr7ZzTBRL0qXri42R4im238Anm6Re1ZUhpo8Fy8XfbpTrMTXbOGxLRZtHNg4YsXAtOKmFaqgkF8NWxQBGRdHQX9ch3rMn71R1xRrutmOWcUs36gLKQMqiSREVhDnKM5KuGu4p/eqI0zV4vmWxTFL+tRbORQBzDU4XeiV0sPgHOwLR4RLWv9PVPd31BSFRtLXEjWZtUzoK2qSHsHx85H/eagTPAFRu8RJ/j0v8W3VIhUrkqibSZJ3KztIAVZx3D7K7IjZREZ+TFRag0UeqnCP1zFk2vLxC/JCb/uAxXGrQI85IUUC6BThH210EO4hLO/WQQUDvo/Q80ay4Bo3d3XT7xo+9wSzuonH+NwAk4nbPycb1890mXDRN5tp9t2sFMV3LhlTuGzSe9CZh8z60t5dcXgSkDZCWeaWkR3uhNWeR6GpBbXBzdIkuznY1AQI/2+gti1nE7L5ECZZfGfChIx7WB/b7f6N9UVw64xVcv3aKGvB2dzUVFaVucdcEkwAcu7yaOfke4ofIe4mJEjMu/5C12RyBSVh/s8vHkicO1hATpvZjW3Zw93BHscZbDBVT0sTqlL1P9won/XvU22TM58+DBLJ4X0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
