appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: eFi7m9gaQBszoo7Mbvth2ewj/DCvL3rozv3PwN43Dok5CvkLlK54X2CojhVb2bK7+cOZjiEZwBdNQfPOjr7ZzTBRL0qXri42R4im238Anm6Re1ZUhpo8Fy8XfbpTrMTXbOGxLRZtHNg4YsXAtOKmFaqgkF8NWxQBGRdHQX9ch3rMn71R1xRrutmOWcUs36gLKQMqiSREVhDnKM5KuGu4p/eqI0zV4vmWxTFL+tRbORQBzDU4XeiV0sPgHOwLR4RLWv9PVPd31BSFRtLXEjWZtUzoK2qSHsHx85H/eagTPAFRu8RJ/j0v8W3VIhUrkqibSZJ3KztIAVZx3D7K7IjZREZ+TFRag0UeqnCP1zFk2vLxC/JCb/uAxXGrQI85IUUC6BThH210EO4hLO/WQQUDvo/Q80ay4Bo3d3XT7xo+9wSzuonH+NwAk4nbPycb1890mXDRN5tp9t2sFMV3LhlTuGzSe9CZh8z60t5dcXgSkDZCWeaWkR3uhNWeR6GpBbXBzdIkuznY1AQI/2+gti1nE7L5ECZZfGfChIx7WB/b7f6N9UVw64xVcv3aKGvB2dzUVFaVucdcEkwAcu7yaOfke4ofIe4mJEjMu/5C12RyBSVh/s8vHkicO1hATpvZjW3Zw93BHscZbDBVT0sTqlL1P9won/XvU22TM58+DBLJ4X0=
